### ISSUE TITLE
Use RDFa-1.1 default namespaces instead of redefining the list

### ISSUE THREAD

**Issue by ansell** [gbv/aREF#5]
The RDFa-1.1 specification includes a list of default namespace/prefix mappings that could be reused instead of redefining the list for aREF [1].

[1] http://www.w3.org/2011/rdfa-context/rdfa-1.1

**Comment by nichtich** [comment]
The list seems not to be stable and it contains a duplicates (http://purl.org/dc/terms/).

**Comment by ansell** [comment]
Fair enough. I haven't noticed any recent changes to the list, but I think it is intended to be updated in future.

**Comment by nichtich** [comment]
see also the list used in linked csv: http://jenit.github.io/linked-csv/#global-property-identifiers

**Comment by nichtich** [comment]
I've included the RDFa-1.1 default list as example in http://gbv.github.io/aREF/aREF.html#namespace-maps.
